### ISSUE TITLE
Script FUBAR 

### ISSUE THREAD

**Issue by 0E800** [jonnyboy/U232-V4-Installer#1]
Ran installer script on Ubuntu Trusty and script completely messed up my dev box. Something in those PPAs your adding uninstalled xfce and removed network-manager.

Not sure what but you should maybe warn users. Maybe remove the -y from your apt-get so people can see whats going to be removed if they continue.

FYI.

**Comment by jonnyboy** [comment]
I apologize. But, for the life of me, I can not see anything that is installed that might conflict with xfce or network manager.

With that said, this script is intended for a server, not a desktop.

I have updated the README to reflect that I have only used this for a clean install of a server, not a desktop.

**Comment by 0E800** [comment]
Thank you for your prompt response. I found another install script and it
worked flawlessly.

https://gitlab.open-scene.net/whocares/u232-v4-xbt-mariadb-php5/blob/master/install.sh



On Fri, Jan 15, 2016 at 1:01 PM, jonnyboy <notifications@github.com> wrote:

> I apologize. But, for the life of me, I can not see anything that is
> installed that might conflict with xfce or network manager.
>
> With that said, this script is intended for a server, not a desktop.
>
> I have updated the README to reflect that I have only used this for a
> clean install of a server, not a desktop.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonnyboy/U232-V4-Installer/issues/1#issuecomment-172091397>
> .
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>

**Comment by jonnyboy** [comment]
Your implication that this script is flawed is misplaced. You used an untested script in a desktop environment, presumably without looking at it first.

I have run this script dozens of times in a server environment flawlessly.

**Comment by 0E800** [comment]
I am not doubting the reliability of your script in a base server
environment only stating that in the environment I 'tested' on, it
destroyed my DM.

I also left an alternative script for folks who DO NOT have your specific
environment. You closed the ticket. Why you still replying?

On Fri, Jan 15, 2016 at 8:08 PM, jonnyboy <notifications@github.com> wrote:

> Your implication that this script is flawed is misplaced. You used an
> untested script in a desktop environment, presumably without looking at it
> first.
>
> I have run this script dozens of times in a server environment flawlessly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonnyboy/U232-V4-Installer/issues/1#issuecomment-172154529>
> .
>



-- 

[image: --]
0E 800
[image: http://]about.me/oe800
<http://about.me/oe800>
